version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "ubuntu-22.04"
        TERRAFORM_DOCS_VERSION: "0.16.0"
        TFSEC_VERSION: "1.28.0"
        TERRASCAN_VERSION: "1.15.2"
        TFLINT_AWS_RULESET_VERSION: "0.21.1"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,lambda,apigateway,iam,acm
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  terraform:
    build:
      context: ../LambdaFunction/.
      dockerfile: Dockerfile
    depends_on:
      - localstack